// @ts-check
import { defineConfig } from 'astro/config';
import { writeFileSync, readdirSync, readFileSync, existsSync } from 'node:fs';
import { resolve } from 'node:path';
import { createPresetsMiddleware, generateWeightsPresetsFile } from './src/lib/admin/presets.ts';

const SHADERS_DIR = 'src/data/boids-shaders';

/** Turn a filename stem into a camelCase import variable name, e.g. "chain-link" → "chainLinkShader" */
function stemToVarName(stem) {
  return stem.replace(/-([a-z])/g, (_, c) => c.toUpperCase()) + 'Shader';
}

/**
 * Normalize CRLF and lone CR to LF so content matching is line-ending
 * agnostic. CodeMirror in the admin editor returns LF, but shader files
 * committed on Windows can be CRLF — without this, "save unchanged" falls
 * through to writing a new file with the preset id.
 */
function normalizeLineEndings(s) {
  return s.replace(/\r\n?/g, '\n');
}

/**
 * Read all .wgsl files from SHADERS_DIR and return a map:
 *   normalized content → { stem, varName }
 * Used to detect when a preset's shader content matches an existing file.
 */
function loadShaderFileMap() {
  const map = new Map(); // content -> { stem, varName }
  if (!existsSync(SHADERS_DIR)) return map;
  for (const f of readdirSync(SHADERS_DIR)) {
    if (!f.endsWith('.wgsl')) continue;
    const stem = f.slice(0, -5);
    const content = readFileSync(resolve(SHADERS_DIR, f), 'utf-8');
    map.set(normalizeLineEndings(content), { stem, varName: stemToVarName(stem) });
  }
  return map;
}

/** @param {import('./src/data/boids-presets').BoidsPreset[]} presets */
function generatePresetsFile(presets) {
  const shaderFileMap = loadShaderFileMap();

  // Resolve each preset's shader to a file reference where possible.
  // Priority: explicit shaderFile > content match > inline string.
  const imports = new Map(); // stem -> varName (only those actually used)

  const resolvedPresets = presets.map(preset => {
    const p = { ...preset };

    if (p.shader) {
      // 1. Content matches an existing file → use that file
      const normalized = normalizeLineEndings(p.shader);
      if (shaderFileMap.has(normalized)) {
        const { stem, varName } = shaderFileMap.get(normalized);
        p.shaderFile = stem;
        delete p.shader;
        imports.set(stem, varName);
        return p;
      }

      // 2. shaderFile is specified → write/overwrite that file, then reference it
      if (p.shaderFile) {
        const filePath = resolve(SHADERS_DIR, `${p.shaderFile}.wgsl`);
        writeFileSync(filePath, p.shader, 'utf-8');
        const varName = stemToVarName(p.shaderFile);
        imports.set(p.shaderFile, varName);
        delete p.shader;
        return p;
      }

      // 3. No match and no shaderFile → auto-save using preset id as filename
      const autoStem = p.id.toLowerCase().replace(/[^a-z0-9-]/g, '-');
      const filePath = resolve(SHADERS_DIR, `${autoStem}.wgsl`);
      writeFileSync(filePath, p.shader, 'utf-8');
      p.shaderFile = autoStem;
      const varName = stemToVarName(autoStem);
      imports.set(autoStem, varName);
      delete p.shader;
    } else if (p.shaderFile) {
      // shaderFile reference with no inline shader — just add the import
      imports.set(p.shaderFile, stemToVarName(p.shaderFile));
    }

    return p;
  });

  // Build import lines
  const importLines = [...imports.entries()]
    .map(([stem, varName]) => `import ${varName} from './boids-shaders/${stem}.wgsl?raw';`)
    .join('\n');

  // Serialize presets, replacing shaderFile-backed entries with variable sentinel
  const SENTINEL = '__SHADER_VAR__';
  const forJson = resolvedPresets.map(p => {
    if (p.shaderFile && imports.has(p.shaderFile)) {
      return { ...p, shader: SENTINEL + imports.get(p.shaderFile) };
    }
    return p;
  });

  let arrJson = JSON.stringify(forJson, null, 2);
  // Replace sentinel strings with bare variable references
  for (const varName of imports.values()) {
    arrJson = arrJson.replaceAll(`"${SENTINEL}${varName}"`, varName);
  }

  return `// AUTO-GENERATED by /admin/boids — do not edit manually
import type { BoidsParams } from '../components/simulations/boids/boids-controller';
${importLines ? '\n' + importLines + '\n' : ''}
export interface BoidsPreset {
  id: string;
  name: string;
  isDefault?: boolean;
  params: BoidsParams;
  trailsEnabled: boolean;
  trailDecay: number;
  shader?: string;
  shaderFile?: string;
}

export const BOIDS_PRESETS: BoidsPreset[] = ${arrJson};
`;
}

export default defineConfig({
  site: 'https://heysoos.github.io',
  vite: {
    // Don't trigger HMR / full-reload when the admin pages write their own
    // auto-generated outputs back to disk — otherwise clicking "Write to disk"
    // reloads the admin page and discards in-memory state. Manual edits
    // outside the admin UI won't hot-reload either, but those files are
    // marked AUTO-GENERATED in CLAUDE.md and should never be hand-edited.
    server: {
      watch: {
        ignored: [
          '**/src/data/boids-presets.ts',
          '**/src/data/boids-shaders/**',
          '**/src/data/cppn-presets.ts',
          '**/src/data/cppn-weights/**',
          '**/src/data/nca-presets.ts',
          '**/src/data/nca-weights/**',
        ],
      },
    },
    plugins: [
      {
        name: 'admin-save-presets',
        configureServer(server) {
          server.middlewares.use(createPresetsMiddleware(
            '/api/admin/save-presets',
            'src/data/boids-presets.ts',
            generatePresetsFile,
          ));
          server.middlewares.use(createPresetsMiddleware(
            '/api/admin/save-cppn-presets',
            'src/data/cppn-presets.ts',
            (presets) => generateWeightsPresetsFile({
              simName: 'cppn',
              typeImportPath: '../components/simulations/cppn/cppn-types',
              typeName: 'CPPNPreset',
              constName: 'CPPN_PRESETS',
              weightsDir: 'src/data/cppn-weights',
              presets,
            }),
          ));
          server.middlewares.use(createPresetsMiddleware(
            '/api/admin/save-nca-presets',
            'src/data/nca-presets.ts',
            (presets) => generateWeightsPresetsFile({
              simName: 'nca',
              typeImportPath: '../components/simulations/nca/nca-types',
              typeName: 'NCAPreset',
              constName: 'NCA_PRESETS',
              weightsDir: 'src/data/nca-weights',
              presets,
            }),
          ));
        },
      },
    ],
  },
});
