// @ts-check
import { defineConfig } from 'astro/config';
import { writeFileSync, readdirSync, readFileSync, existsSync } from 'node:fs';
import { resolve, basename } from 'node:path';

const SHADERS_DIR = 'src/data/boids-shaders';

/** Turn a filename stem into a camelCase import variable name, e.g. "chain-link" → "chainLinkShader" */
function stemToVarName(stem) {
  return stem.replace(/-([a-z])/g, (_, c) => c.toUpperCase()) + 'Shader';
}

/**
 * Read all .wgsl files from SHADERS_DIR and return a map:
 *   content → { stem, varName }
 * Used to detect when a preset's shader content matches an existing file.
 */
function loadShaderFileMap() {
  const map = new Map(); // content -> { stem, varName }
  if (!existsSync(SHADERS_DIR)) return map;
  for (const f of readdirSync(SHADERS_DIR)) {
    if (!f.endsWith('.wgsl')) continue;
    const stem = f.slice(0, -5);
    const content = readFileSync(resolve(SHADERS_DIR, f), 'utf-8');
    map.set(content, { stem, varName: stemToVarName(stem) });
  }
  return map;
}

/** @param {import('./src/data/boids-presets').BoidsPreset[]} presets */
function generatePresetsFile(presets) {
  const shaderFileMap = loadShaderFileMap();

  // Resolve each preset's shader to a file reference where possible.
  // Priority: explicit shaderFile > content match > inline string.
  const imports = new Map(); // stem -> varName (only those actually used)

  const resolvedPresets = presets.map(preset => {
    const p = { ...preset };

    if (p.shader) {
      // 1. Content matches an existing file → use that file
      if (shaderFileMap.has(p.shader)) {
        const { stem, varName } = shaderFileMap.get(p.shader);
        p.shaderFile = stem;
        delete p.shader;
        imports.set(stem, varName);
        return p;
      }

      // 2. shaderFile is specified → write/overwrite that file, then reference it
      if (p.shaderFile) {
        const filePath = resolve(SHADERS_DIR, `${p.shaderFile}.wgsl`);
        writeFileSync(filePath, p.shader, 'utf-8');
        const varName = stemToVarName(p.shaderFile);
        imports.set(p.shaderFile, varName);
        delete p.shader;
        return p;
      }

      // 3. No match and no shaderFile → inline (legacy / truly one-off)
      // shader stays as-is
    } else if (p.shaderFile) {
      // shaderFile reference with no inline shader — just add the import
      imports.set(p.shaderFile, stemToVarName(p.shaderFile));
    }

    return p;
  });

  // Build import lines
  const importLines = [...imports.entries()]
    .map(([stem, varName]) => `import ${varName} from './boids-shaders/${stem}.wgsl?raw';`)
    .join('\n');

  // Serialize presets, replacing shaderFile-backed entries with variable sentinel
  const SENTINEL = '__SHADER_VAR__';
  const forJson = resolvedPresets.map(p => {
    if (p.shaderFile && imports.has(p.shaderFile)) {
      return { ...p, shader: SENTINEL + imports.get(p.shaderFile) };
    }
    return p;
  });

  let arrJson = JSON.stringify(forJson, null, 2);
  // Replace sentinel strings with bare variable references
  for (const varName of imports.values()) {
    arrJson = arrJson.replaceAll(`"${SENTINEL}${varName}"`, varName);
  }

  return `// AUTO-GENERATED by /admin/boids — do not edit manually
import type { BoidsParams } from '../components/simulations/boids/boids-controller';
${importLines ? '\n' + importLines + '\n' : ''}
export interface BoidsPreset {
  id: string;
  name: string;
  isDefault?: boolean;
  params: BoidsParams;
  trailsEnabled: boolean;
  trailDecay: number;
  shader?: string;
  shaderFile?: string;
}

export const BOIDS_PRESETS: BoidsPreset[] = ${arrJson};
`;
}

export default defineConfig({
  site: 'https://heysoos.github.io',
  vite: {
    plugins: [
      {
        name: 'admin-save-presets',
        configureServer(server) {
          server.middlewares.use('/api/admin/save-presets', async (req, res) => {
            if (req.method !== 'POST') {
              res.statusCode = 405;
              res.end();
              return;
            }
            try {
              const chunks = [];
              for await (const chunk of req) chunks.push(chunk);
              const presets = JSON.parse(Buffer.concat(chunks).toString());
              const filePath = resolve('src/data/boids-presets.ts');
              writeFileSync(filePath, generatePresetsFile(presets), 'utf-8');
              res.statusCode = 200;
              res.setHeader('Content-Type', 'application/json');
              res.end(JSON.stringify({ ok: true }));
            } catch (err) {
              console.error('[admin-save-presets]', err);
              res.statusCode = 500;
              res.end(JSON.stringify({ error: String(err) }));
            }
          });
        },
      },
    ],
  },
});
