// src/components/simulations/nca/nca-codegen.ts
import type { NCAConfig, NCAActivation, NCAWeightLayout } from './nca-types';

export function computeWeightLayout(config: NCAConfig): NCAWeightLayout {
  const { channels, hidden, filters } = config;
  const nFilters = [filters.identity, filters.sobelX, filters.sobelY, filters.laplacian]
    .filter(Boolean).length;
  const w1BiasOffset = channels * nFilters * hidden;
  const w2Offset = w1BiasOffset + hidden;
  const totalCount = w2Offset + hidden * channels;
  return { nFilters, w1Offset: 0, w1BiasOffset, w2Offset, totalCount };
}

// vec4 activation — applied element-wise, used in packed hidden layer
function actFn4(a: NCAActivation): string {
  if (a === 'relu')      return 'fn act4(x: vec4f) -> vec4f { return max(vec4f(0.0), x); }';
  if (a === 'tanh')      return 'fn act4(x: vec4f) -> vec4f { return vec4f(tanh(x.x), tanh(x.y), tanh(x.z), tanh(x.w)); }';
  /* leakyrelu */        return 'fn act4(x: vec4f) -> vec4f { return select(x * 0.01, x, x > vec4f(0.0)); }';
}

function buildPerceptionCode(config: NCAConfig, nFilters: number): string {
  const { filters } = config;
  const lines: string[] = [];
  let fi = 0;
  const p = (idx: number, expr: string) =>
    `    perc[c * ${nFilters}u + ${idx}u] = ${expr};`;

  if (filters.identity) {
    lines.push(p(fi++, 'readState(xi, yi, c)'));
  }
  if (filters.sobelX) {
    lines.push(p(fi++,
      '(-1.0*readState(xi-1,yi-1,c) + readState(xi+1,yi-1,c) +\n' +
      '      -2.0*readState(xi-1,yi,c)   + 2.0*readState(xi+1,yi,c) +\n' +
      '      -1.0*readState(xi-1,yi+1,c) + readState(xi+1,yi+1,c)) / 8.0'));
  }
  if (filters.sobelY) {
    lines.push(p(fi++,
      '(-1.0*readState(xi-1,yi-1,c) - 2.0*readState(xi,yi-1,c) - readState(xi+1,yi-1,c) +\n' +
      '       readState(xi-1,yi+1,c) + 2.0*readState(xi,yi+1,c) + readState(xi+1,yi+1,c)) / 8.0'));
  }
  if (filters.laplacian) {
    lines.push(p(fi++,
      '(readState(xi-1,yi-1,c) + 2.0*readState(xi,yi-1,c) + readState(xi+1,yi-1,c) +\n' +
      '       2.0*readState(xi-1,yi,c) - 12.0*readState(xi,yi,c) + 2.0*readState(xi+1,yi,c) +\n' +
      '       readState(xi-1,yi+1,c) + 2.0*readState(xi,yi+1,c) + readState(xi+1,yi+1,c)) / 16.0'));
  }
  return lines.join('\n');
}

// Uniforms struct shared by both shaders (12 x f32/u32 = 48 bytes, 16-byte aligned)
const UNIFORMS_STRUCT = `struct Uniforms {
  fireRate       : f32,
  dt             : f32,
  frameIndex     : u32,
  gridW          : u32,
  gridH          : u32,
  channelR       : u32,
  channelG       : u32,
  channelB       : u32,
  normalizeDisplay: u32,
  _pad0          : u32,
  _pad1          : u32,
  _pad2          : u32,
}`;

export function generateComputeShader(config: NCAConfig): string {
  const { channels, hidden } = config;
  const layout = computeWeightLayout(config);
  const { nFilters, w1BiasOffset, w2Offset } = layout;
  const percCode = buildPerceptionCode(config, nFilters);

  // All divisible by 4 is guaranteed by our supported channel/hidden options
  const perception = channels * nFilters;
  const hidden4    = hidden / 4;
  const w1BiasOff4 = w1BiasOffset / 4;  // offset into vec4 weight array
  const w2Off4     = w2Offset     / 4;  // offset into vec4 weight array

  return `// GENERATED by nca-codegen.ts — do not edit
const CHANNELS    : u32 = ${channels}u;
const HIDDEN_4    : u32 = ${hidden4}u;      // HIDDEN / 4 — hidden layer packed as vec4
const N_FILTERS   : u32 = ${nFilters}u;
const PERCEPTION  : u32 = ${perception}u;   // CHANNELS * N_FILTERS
const W1_BIAS_OFF4: u32 = ${w1BiasOff4}u;  // bias start in vec4 weight array
const W2_OFF4     : u32 = ${w2Off4}u;      // W2 start in vec4 weight array

// vec4 activation — one call handles 4 hidden units simultaneously
${actFn4(config.activation)}

${UNIFORMS_STRUCT}

@group(0) @binding(0) var<storage, read>       stateIn : array<f32>;
@group(0) @binding(1) var<storage, read_write> stateOut: array<f32>;
// Weights stored as vec4 array.  Layout:
//   [0, W1_BIAS_OFF4)      W1: [PERCEPTION, HIDDEN_4] — row i, group hi4
//   [W1_BIAS_OFF4, W2_OFF4) B1: [HIDDEN_4]
//   [W2_OFF4, …)           W2: [CHANNELS, HIDDEN_4]  — row c, group hi4
@group(0) @binding(2) var<storage, read>       weights : array<vec4f>;
@group(0) @binding(3) var<uniform>             u       : Uniforms;

fn pcg(v: u32) -> u32 {
  var x = v * 747796405u + 2891336453u;
  x = ((x >> ((x >> 28u) + 4u)) ^ x) * 277803737u;
  return (x >> 22u) ^ x;
}

fn readState(xi: i32, yi: i32, c: u32) -> f32 {
  let x = u32((xi + i32(u.gridW)) % i32(u.gridW));
  let y = u32((yi + i32(u.gridH)) % i32(u.gridH));
  return stateIn[(y * u.gridW + x) * CHANNELS + c];
}

@compute @workgroup_size(16, 16)
fn main(@builtin(global_invocation_id) id: vec3<u32>) {
  if (id.x >= u.gridW || id.y >= u.gridH) { return; }
  let xi   = i32(id.x);
  let yi   = i32(id.y);
  let cell = id.y * u.gridW + id.x;
  let base = cell * CHANNELS;

  // Stochastic mask
  let rng = pcg(cell ^ u.frameIndex);
  if (f32(rng) / 4294967295.0 >= u.fireRate) {
    for (var c = 0u; c < CHANNELS; c++) { stateOut[base + c] = stateIn[base + c]; }
    return;
  }

  // Perception — scalar array, one entry per (channel, filter) pair
  var perc: array<f32, ${perception}u>;
  for (var c = 0u; c < CHANNELS; c++) {
${percCode}
  }

  // MLP layer 1: [PERCEPTION → HIDDEN], hidden packed as vec4
  // W1 layout: weights[i * HIDDEN_4 + hi4] = vec4 of 4 consecutive hidden weights
  // This matches the flat [PERCEPTION, HIDDEN] row-major layout reinterpreted as vec4.
  var h: array<vec4f, ${hidden4}u>;
  for (var hi4 = 0u; hi4 < HIDDEN_4; hi4++) {
    var s = weights[W1_BIAS_OFF4 + hi4];  // bias vec4
    for (var i = 0u; i < PERCEPTION; i++) {
      s += perc[i] * weights[i * HIDDEN_4 + hi4];
    }
    h[hi4] = act4(s);
  }

  // MLP layer 2: [HIDDEN → CHANNELS], residual update
  // W2 layout: weights[W2_OFF4 + c * HIDDEN_4 + hi4] = vec4(W2[c, hi4*4..hi4*4+3])
  // Stored as [CHANNELS, HIDDEN] row-major — transpose of previous [HIDDEN, CHANNELS].
  for (var c = 0u; c < CHANNELS; c++) {
    var d = 0.0;
    for (var hi4 = 0u; hi4 < HIDDEN_4; hi4++) {
      d += dot(h[hi4], weights[W2_OFF4 + c * HIDDEN_4 + hi4]);
    }
    stateOut[base + c] = clamp(stateIn[base + c] + u.dt * d, 0.0, 1.0);
  }
}
`;
}

export function generateRenderShader(config: NCAConfig): string {
  const { channels } = config;
  return `// GENERATED by nca-codegen.ts — do not edit
const CHANNELS: u32 = ${channels}u;

${UNIFORMS_STRUCT}

@group(0) @binding(0) var<storage, read> state: array<f32>;
@group(0) @binding(1) var<uniform>       u    : Uniforms;

@vertex
fn vs(@builtin(vertex_index) vi: u32) -> @builtin(position) vec4f {
  var pos = array<vec2f, 6>(
    vec2f(-1.0,-1.0), vec2f(1.0,-1.0), vec2f(-1.0,1.0),
    vec2f(-1.0,1.0),  vec2f(1.0,-1.0), vec2f(1.0,1.0)
  );
  return vec4f(pos[vi], 0.0, 1.0);
}

@fragment
fn fs(@builtin(position) pos: vec4f) -> @location(0) vec4f {
  let x    = u32(pos.x);
  let y    = u32(pos.y);
  let cell = y * u.gridW + x;
  var r = state[cell * CHANNELS + u.channelR];
  var g = state[cell * CHANNELS + u.channelG];
  var b = state[cell * CHANNELS + u.channelB];
  return vec4f(r, g, b, 1.0);
}
`;
}

// Xavier uniform weight initialisation
// W1: [PERCEPTION, HIDDEN] row-major  (reinterpreted as vec4 in shader)
// B1: [HIDDEN]
// W2: [CHANNELS, HIDDEN] row-major    (transposed vs. old [HIDDEN, CHANNELS])
export function generateWeights(config: NCAConfig, seed: number): Float32Array {
  const { channels, hidden } = config;
  const layout = computeWeightLayout(config);
  const { nFilters, w1BiasOffset, w2Offset, totalCount } = layout;
  const weights = new Float32Array(totalCount);

  // mulberry32 PRNG
  let s = seed >>> 0;
  const rand = () => {
    s += 0x6d2b79f5;
    let t = Math.imul(s ^ (s >>> 15), 1 | s);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
  const xavier = (fanIn: number, fanOut: number) => {
    const limit = Math.sqrt(6 / (fanIn + fanOut));
    return rand() * 2 * limit - limit;
  };

  const w1In = channels * nFilters;
  // W1: [w1In, hidden] — fills the same flat region, layout compatible with vec4 reinterpretation
  for (let i = 0; i < w1In * hidden; i++) weights[i] = xavier(w1In, hidden);
  // B1: zeros (already zero-filled)
  // W2: [channels, hidden] — note: transposed from old [hidden, channels]
  for (let c = 0; c < channels; c++) {
    for (let hi = 0; hi < hidden; hi++) {
      weights[w2Offset + c * hidden + hi] = xavier(hidden, channels);
    }
  }

  return weights;
}
