// src/components/simulations/nca/nca-codegen.ts
import type { NCAConfig, NCAActivation, NCAWeightLayout } from './nca-types';

export function computeWeightLayout(config: NCAConfig): NCAWeightLayout {
  const { channels, hidden, filters } = config;
  const nFilters = [filters.identity, filters.sobelX, filters.sobelY, filters.laplacian]
    .filter(Boolean).length;
  const w1BiasOffset = channels * nFilters * hidden;
  const w2Offset = w1BiasOffset + hidden;
  const totalCount = w2Offset + hidden * channels;
  return { nFilters, w1Offset: 0, w1BiasOffset, w2Offset, totalCount };
}

function actFn(a: NCAActivation): string {
  if (a === 'relu')      return 'fn act(x: f32) -> f32 { return max(0.0, x); }';
  if (a === 'tanh')      return 'fn act(x: f32) -> f32 { return tanh(x); }';
  /* leakyrelu */        return 'fn act(x: f32) -> f32 { return select(x * 0.01, x, x > 0.0); }';
}

function buildPerceptionCode(config: NCAConfig, nFilters: number): string {
  const { filters } = config;
  const lines: string[] = [];
  let fi = 0;
  const p = (idx: number, expr: string) =>
    `    perc[c * ${nFilters}u + ${idx}u] = ${expr};`;

  if (filters.identity) {
    lines.push(p(fi++, 'readState(xi, yi, c)'));
  }
  if (filters.sobelX) {
    lines.push(p(fi++,
      '(-1.0*readState(xi-1,yi-1,c) + readState(xi+1,yi-1,c) +\n' +
      '      -2.0*readState(xi-1,yi,c)   + 2.0*readState(xi+1,yi,c) +\n' +
      '      -1.0*readState(xi-1,yi+1,c) + readState(xi+1,yi+1,c)) / 8.0'));
  }
  if (filters.sobelY) {
    lines.push(p(fi++,
      '(-1.0*readState(xi-1,yi-1,c) - 2.0*readState(xi,yi-1,c) - readState(xi+1,yi-1,c) +\n' +
      '       readState(xi-1,yi+1,c) + 2.0*readState(xi,yi+1,c) + readState(xi+1,yi+1,c)) / 8.0'));
  }
  if (filters.laplacian) {
    lines.push(p(fi++,
      '(readState(xi-1,yi-1,c) + 2.0*readState(xi,yi-1,c) + readState(xi+1,yi-1,c) +\n' +
      '       2.0*readState(xi-1,yi,c) - 12.0*readState(xi,yi,c) + 2.0*readState(xi+1,yi,c) +\n' +
      '       readState(xi-1,yi+1,c) + 2.0*readState(xi,yi+1,c) + readState(xi+1,yi+1,c)) / 16.0'));
  }
  return lines.join('\n');
}

// Uniforms struct shared by both shaders (12 x f32/u32 = 48 bytes, 16-byte aligned)
const UNIFORMS_STRUCT = `struct Uniforms {
  fireRate       : f32,
  dt             : f32,
  frameIndex     : u32,
  gridW          : u32,
  gridH          : u32,
  channelR       : u32,
  channelG       : u32,
  channelB       : u32,
  normalizeDisplay: u32,
  _pad0          : u32,
  _pad1          : u32,
  _pad2          : u32,
}`;

export function generateComputeShader(config: NCAConfig): string {
  const { channels, hidden } = config;
  const layout = computeWeightLayout(config);
  const { nFilters, w1BiasOffset, w2Offset } = layout;
  const percCode = buildPerceptionCode(config, nFilters);

  return `// GENERATED by nca-codegen.ts — do not edit
const CHANNELS   : u32 = ${channels}u;
const HIDDEN     : u32 = ${hidden}u;
const N_FILTERS  : u32 = ${nFilters}u;
const W1_BIAS_OFF: u32 = ${w1BiasOffset}u;
const W2_OFF     : u32 = ${w2Offset}u;

${actFn(config.activation)}

${UNIFORMS_STRUCT}

@group(0) @binding(0) var<storage, read>       stateIn : array<f32>;
@group(0) @binding(1) var<storage, read_write> stateOut: array<f32>;
@group(0) @binding(2) var<storage, read>       weights : array<f32>;
@group(0) @binding(3) var<uniform>             u       : Uniforms;

fn pcg(v: u32) -> u32 {
  var x = v * 747796405u + 2891336453u;
  x = ((x >> ((x >> 28u) + 4u)) ^ x) * 277803737u;
  return (x >> 22u) ^ x;
}

fn readState(xi: i32, yi: i32, c: u32) -> f32 {
  let x = u32((xi + i32(u.gridW)) % i32(u.gridW));
  let y = u32((yi + i32(u.gridH)) % i32(u.gridH));
  return stateIn[(y * u.gridW + x) * CHANNELS + c];
}

@compute @workgroup_size(8, 8)
fn main(@builtin(global_invocation_id) id: vec3<u32>) {
  if (id.x >= u.gridW || id.y >= u.gridH) { return; }
  let xi   = i32(id.x);
  let yi   = i32(id.y);
  let cell = id.y * u.gridW + id.x;
  let base = cell * CHANNELS;

  // Stochastic mask
  let rng = pcg(cell ^ u.frameIndex);
  if (f32(rng) / 4294967295.0 >= u.fireRate) {
    for (var c = 0u; c < CHANNELS; c++) { stateOut[base + c] = stateIn[base + c]; }
    return;
  }

  // Perception
  var perc: array<f32, CHANNELS * N_FILTERS>;
  for (var c = 0u; c < CHANNELS; c++) {
${percCode}
  }

  // MLP layer 1: [CHANNELS*N_FILTERS → HIDDEN]
  var h: array<f32, HIDDEN>;
  for (var hi = 0u; hi < HIDDEN; hi++) {
    var s = weights[W1_BIAS_OFF + hi];
    for (var i = 0u; i < CHANNELS * N_FILTERS; i++) {
      s += perc[i] * weights[i * HIDDEN + hi];
    }
    h[hi] = act(s);
  }

  // MLP layer 2: [HIDDEN → CHANNELS], residual update
  for (var c = 0u; c < CHANNELS; c++) {
    var d = 0.0;
    for (var hi = 0u; hi < HIDDEN; hi++) {
      d += h[hi] * weights[W2_OFF + hi * CHANNELS + c];
    }
    stateOut[base + c] = clamp(stateIn[base + c] + u.dt * d, 0.0, 1.0);
  }
}
`;
}

export function generateRenderShader(config: NCAConfig): string {
  const { channels } = config;
  return `// GENERATED by nca-codegen.ts — do not edit
const CHANNELS: u32 = ${channels}u;

${UNIFORMS_STRUCT}

@group(0) @binding(0) var<storage, read> state: array<f32>;
@group(0) @binding(1) var<uniform>       u    : Uniforms;

@vertex
fn vs(@builtin(vertex_index) vi: u32) -> @builtin(position) vec4f {
  var pos = array<vec2f, 6>(
    vec2f(-1.0,-1.0), vec2f(1.0,-1.0), vec2f(-1.0,1.0),
    vec2f(-1.0,1.0),  vec2f(1.0,-1.0), vec2f(1.0,1.0)
  );
  return vec4f(pos[vi], 0.0, 1.0);
}

@fragment
fn fs(@builtin(position) pos: vec4f) -> @location(0) vec4f {
  let x    = u32(pos.x);
  let y    = u32(pos.y);
  let cell = y * u.gridW + x;
  var r = state[cell * CHANNELS + u.channelR];
  var g = state[cell * CHANNELS + u.channelG];
  var b = state[cell * CHANNELS + u.channelB];
  return vec4f(r, g, b, 1.0);
}
`;
}

// Xavier uniform weight initialisation
export function generateWeights(config: NCAConfig, seed: number): Float32Array {
  const { channels, hidden } = config;
  const layout = computeWeightLayout(config);
  const { nFilters, w1BiasOffset, w2Offset, totalCount } = layout;
  const weights = new Float32Array(totalCount);

  // mulberry32 PRNG
  let s = seed >>> 0;
  const rand = () => {
    s += 0x6d2b79f5;
    let t = Math.imul(s ^ (s >>> 15), 1 | s);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
  const xavier = (fanIn: number, fanOut: number) => {
    const limit = Math.sqrt(6 / (fanIn + fanOut));
    return rand() * 2 * limit - limit;
  };

  const w1In = channels * nFilters;
  // W1 weights [w1In × HIDDEN]
  for (let i = 0; i < w1In * hidden; i++) weights[i] = xavier(w1In, hidden);
  // W1 biases — zeros (Float32Array already zero-filled)
  // W2 weights [HIDDEN × CHANNELS]
  for (let i = 0; i < hidden * channels; i++) weights[w2Offset + i] = xavier(hidden, channels);

  return weights;
}
