// src/lib/admin/presets.ts
// Node.js utilities used by astro.config.mjs — not browser code.
import { writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { resolve } from 'node:path';
import type { Connect } from 'vite';

/**
 * Generic factory for admin POST middleware. Reads the request body as JSON,
 * calls `generator`, and writes the result to `outputPath`.
 */
export function createPresetsMiddleware(
  route: string,
  outputPath: string,
  generator: (data: unknown) => string,
): Connect.NextHandleFunction {
  return async (req, res, next) => {
    if (req.url !== route) { next(); return; }
    if (req.method !== 'POST') { res.statusCode = 405; res.end(); return; }
    try {
      const chunks: Buffer[] = [];
      for await (const chunk of req) chunks.push(chunk as Buffer);
      const data = JSON.parse(Buffer.concat(chunks).toString());
      writeFileSync(resolve(outputPath), generator(data), 'utf-8');
      res.statusCode = 200;
      res.setHeader('Content-Type', 'application/json');
      res.end(JSON.stringify({ ok: true }));
    } catch (err) {
      console.error(`[${route}]`, err);
      res.statusCode = 500;
      res.end(JSON.stringify({ error: String(err) }));
    }
  };
}

/** Convert a kebab-case id to a camelCase weights variable name: "soft-colors" → "softColorsWeights" */
export function idToWeightsVarName(id: string): string {
  return id.replace(/-([a-z])/g, (_, c: string) => c.toUpperCase()) + 'Weights';
}

/**
 * Shared generator for CPPN and NCA presets — both follow the same pattern:
 * extract weights into per-id JSON files, then emit an import-based TS file.
 */
export function generateWeightsPresetsFile(opts: {
  simName: string;       // 'cppn' | 'nca'
  typeImportPath: string; // '../components/simulations/cppn/cppn-types'
  typeName: string;       // 'CPPNPreset' | 'NCAPreset'
  constName: string;     // 'CPPN_PRESETS' | 'NCA_PRESETS'
  weightsDir: string;    // 'src/data/cppn-weights'
  presets: Array<{ id: string; weights: unknown; [key: string]: unknown }>;
}): string {
  const { typeImportPath, typeName, constName, weightsDir, presets } = opts;

  if (!existsSync(weightsDir)) mkdirSync(weightsDir, { recursive: true });

  const SENTINEL = '__WEIGHTS_VAR__';
  const imports: Array<{ id: string; varName: string }> = [];

  const presetsWithoutWeights = presets.map(preset => {
    const { weights, ...rest } = preset;
    writeFileSync(
      resolve(weightsDir, `${preset.id}.json`),
      JSON.stringify(weights, null, 2) + '\n',
      'utf-8',
    );
    const varName = idToWeightsVarName(preset.id);
    imports.push({ id: preset.id, varName });
    return { ...rest, weights: `${SENTINEL}${varName}` };
  });

  const importLines = imports
    .map(({ id, varName }) => `import ${varName} from './${opts.simName}-weights/${id}.json';`)
    .join('\n');

  let arrJson = JSON.stringify(presetsWithoutWeights, null, 2);
  for (const { varName } of imports) {
    arrJson = arrJson.replaceAll(`"${SENTINEL}${varName}"`, varName);
  }

  return `// AUTO-GENERATED by /admin/${opts.simName} — do not edit manually
import type { ${typeName} } from '${typeImportPath}';

${importLines}

export type { ${typeName} };

export const ${constName}: ${typeName}[] = ${arrJson};
`;
}
