// AUTO-GENERATED by /admin/boids — do not edit manually
import type { BoidsParams } from '../components/simulations/boids/boids-controller';

export interface BoidsPreset {
  id: string;
  name: string;
  isDefault?: boolean;
  params: BoidsParams;
  trailsEnabled: boolean;
  trailDecay: number;
  shader?: string;
}

export const BOIDS_PRESETS: BoidsPreset[] = [
  {
    "id": "pink-metal-1775549969719",
    "name": "Pink Metal",
    "params": {
      "dt": 0.016,
      "numParticles": 2000,
      "attractionRadius": 0.2,
      "repulsionRadius": 0.05,
      "attraction": 0.3,
      "repulsion": 1.5,
      "alignment": 0.1,
      "friction": 2,
      "maxSpeed": 0.22,
      "mouseRadius": 0.15,
      "coneAngle": -0.5,
      "size": 0.005,
      "shapeId": 0,
      "colorR": 0.88,
      "colorG": 0.31,
      "colorB": 0.5
    },
    "trailsEnabled": true,
    "trailDecay": 0.92,
    "isDefault": false
  },
  {
    "id": "metropolitan",
    "name": "Metropolitan",
    "params": {
      "dt": 0.016,
      "numParticles": 2000,
      "attractionRadius": 0.6,
      "repulsionRadius": 0.02,
      "attraction": 0.42,
      "repulsion": 1.85,
      "alignment": 0.15,
      "friction": 2,
      "maxSpeed": 0.16,
      "mouseRadius": 0.15,
      "coneAngle": 0.8,
      "size": 0.005,
      "shapeId": 0,
      "colorR": 0.49411764705882355,
      "colorG": 0.7372549019607844,
      "colorB": 0.8862745098039215
    },
    "trailsEnabled": true,
    "trailDecay": 0.92,
    "isDefault": true
  },
  {
    "id": "porosity",
    "name": "Porosity",
    "params": {
      "dt": 0.016,
      "numParticles": 2000,
      "attractionRadius": 0.08,
      "repulsionRadius": 0.03,
      "attraction": 0.68,
      "repulsion": 5,
      "alignment": 0.15,
      "friction": 2,
      "maxSpeed": 0.15,
      "mouseRadius": 0.5,
      "coneAngle": -0.2,
      "size": 0.005,
      "shapeId": 0,
      "colorR": 0.88,
      "colorG": 0.63,
      "colorB": 0.25
    },
    "trailsEnabled": true,
    "trailDecay": 0.92
  }
];
