// AUTO-GENERATED by /admin/boids � do not edit manually
import type { BoidsParams } from '../components/simulations/boids/boids-controller';

import oscillatorShader from './boids-shaders/oscillator.wgsl?raw';
import oscillator2Shader from './boids-shaders/oscillator2.wgsl?raw';
import chainLinkShader from './boids-shaders/chain-link.wgsl?raw';
import abstractJellyfishShader from './boids-shaders/abstract-jellyfish.wgsl?raw';
import fishoniumShader from './boids-shaders/fishonium.wgsl?raw';
import snakeShader from './boids-shaders/snake.wgsl?raw';
import particlebahnShader from './boids-shaders/particlebahn.wgsl?raw';

export interface BoidsPreset {
  id: string;
  name: string;
  isDefault?: boolean;
  params: BoidsParams;
  trailsEnabled: boolean;
  trailDecay: number;
  shader?: string;
  shaderFile?: string;
}

export const BOIDS_PRESETS: BoidsPreset[] = [
  {
    "id": "old-default",
    "name": "Old Default",
    "isDefault": false,
    "params": {
      "dt": 0.016,
      "numParticles": 200,
      "attractionRadius": 0.2,
      "repulsionRadius": 0.05,
      "attraction": 0.3,
      "repulsion": 1.5,
      "alignment": 0.1,
      "friction": 2,
      "maxSpeed": 0.22,
      "mouseRadius": 0.15,
      "coneAngle": -0.5,
      "size": 0.02,
      "shapeId": 0,
      "colorR": 0.88,
      "colorG": 0.63,
      "colorB": 0.25,
      "opacity": 1.0,
      "opacityMode": 0
    },
    "trailsEnabled": false,
    "trailDecay": 0.92
  },
  {
    "id": "pink-metal-1775549969719",
    "name": "Pink Metal",
    "params": {
      "dt": 0.016,
      "numParticles": 2000,
      "attractionRadius": 0.2,
      "repulsionRadius": 0.05,
      "attraction": 0.3,
      "repulsion": 1.5,
      "alignment": 0.1,
      "friction": 2,
      "maxSpeed": 0.22,
      "mouseRadius": 0.15,
      "coneAngle": -0.5,
      "size": 0.005,
      "shapeId": 0,
      "colorR": 0.88,
      "colorG": 0.31,
      "colorB": 0.5,
      "opacity": 1.0,
      "opacityMode": 0
    },
    "trailsEnabled": true,
    "trailDecay": 0.92,
    "isDefault": true
  },
  {
    "id": "metropolitan",
    "name": "Metropolitan",
    "params": {
      "dt": 0.016,
      "numParticles": 2000,
      "attractionRadius": 0.6,
      "repulsionRadius": 0.02,
      "attraction": 0.42,
      "repulsion": 1.85,
      "alignment": 0.15,
      "friction": 2,
      "maxSpeed": 0.16,
      "mouseRadius": 0.15,
      "coneAngle": 0.8,
      "size": 0.005,
      "shapeId": 0,
      "colorR": 0.49411764705882355,
      "colorG": 0.7372549019607844,
      "colorB": 0.8862745098039215,
      "opacity": 1.0,
      "opacityMode": 0
    },
    "trailsEnabled": true,
    "trailDecay": 0.92,
    "isDefault": false
  },
  {
    "id": "porosity",
    "name": "Porosity",
    "params": {
      "dt": 0.016,
      "numParticles": 2000,
      "attractionRadius": 0.08,
      "repulsionRadius": 0.03,
      "attraction": 0.68,
      "repulsion": 5,
      "alignment": 0.15,
      "friction": 2,
      "maxSpeed": 0.15,
      "mouseRadius": 0.5,
      "coneAngle": -0.2,
      "size": 0.005,
      "shapeId": 0,
      "colorR": 0.88,
      "colorG": 0.63,
      "colorB": 0.25,
      "opacity": 1.0,
      "opacityMode": 0
    },
    "trailsEnabled": true,
    "trailDecay": 0.92,
    "isDefault": false
  },
  {
    "id": "oscillator",
    "name": "Oscillator",
    "params": {
      "dt": 0.016,
      "numParticles": 5000,
      "attractionRadius": 0.05,
      "repulsionRadius": 0.03,
      "attraction": 0.21,
      "repulsion": 4.9,
      "alignment": 0.48,
      "friction": 2,
      "maxSpeed": 0.15,
      "mouseRadius": 0.5,
      "coneAngle": 0.6,
      "size": 0.005,
      "shapeId": 0,
      "colorR": 0.88,
      "colorG": 0.63,
      "colorB": 0.25,
      "opacity": 1.0,
      "opacityMode": 0
    },
    "trailsEnabled": true,
    "trailDecay": 0.92,
    "isDefault": false,
    "shaderFile": "oscillator",
    "shader": oscillatorShader
  },
  {
    "id": "oscillator2",
    "name": "Oscillator2",
    "params": {
      "dt": 0.016,
      "numParticles": 5000,
      "attractionRadius": 0.1,
      "repulsionRadius": 0.03,
      "attraction": 0.21,
      "repulsion": 4.9,
      "alignment": 1,
      "friction": 2,
      "maxSpeed": 0.15,
      "mouseRadius": 0.5,
      "coneAngle": 0.95,
      "size": 0.005,
      "shapeId": 0,
      "colorR": 0.88,
      "colorG": 0.63,
      "colorB": 0.25,
      "opacity": 1.0,
      "opacityMode": 0
    },
    "trailsEnabled": true,
    "trailDecay": 0.92,
    "isDefault": false,
    "shaderFile": "oscillator2",
    "shader": oscillator2Shader
  },
  {
    "id": "chain-link",
    "name": "Chain Link",
    "params": {
      "dt": 0.016,
      "numParticles": 5000,
      "attractionRadius": 0.44,
      "repulsionRadius": 0.155,
      "attraction": 0.9,
      "repulsion": 1.75,
      "alignment": 0.39,
      "friction": 2,
      "maxSpeed": 0.18,
      "mouseRadius": 0.5,
      "coneAngle": 0.4,
      "size": 0.005,
      "shapeId": 0,
      "colorR": 1,
      "colorG": 1,
      "colorB": 1,
      "opacity": 1.0,
      "opacityMode": 0
    },
    "trailsEnabled": false,
    "trailDecay": 0.95,
    "isDefault": false,
    "shaderFile": "chain-link",
    "shader": chainLinkShader
  },
  {
    "id": "abstract-jellyfish",
    "name": "Abstract Jellyfish",
    "params": {
      "dt": 0.019,
      "numParticles": 1000,
      "attractionRadius": 0.6,
      "repulsionRadius": 0.3,
      "attraction": 1.66,
      "repulsion": 2.15,
      "alignment": 1,
      "friction": 2,
      "maxSpeed": 0.18,
      "mouseRadius": 0.5,
      "coneAngle": -0.7,
      "size": 0.005,
      "shapeId": 1,
      "colorR": 0.88,
      "colorG": 0.31,
      "colorB": 0.5,
      "opacity": 1.0,
      "opacityMode": 0
    },
    "trailsEnabled": false,
    "trailDecay": 0.95,
    "isDefault": false,
    "shaderFile": "abstract-jellyfish",
    "shader": abstractJellyfishShader
  },
  {
    "id": "fishonium",
    "name": "Fishonium",
    "params": {
      "dt": 0.019,
      "numParticles": 500,
      "attractionRadius": 0.44,
      "repulsionRadius": 0.135,
      "attraction": 0.21,
      "repulsion": 0.4,
      "alignment": 0.29,
      "friction": 6,
      "maxSpeed": 0.15,
      "mouseRadius": 0.5,
      "coneAngle": -0.7,
      "size": 0.005,
      "shapeId": 1,
      "colorR": 0.31,
      "colorG": 0.78,
      "colorB": 0.47,
      "opacity": 1.0,
      "opacityMode": 0
    },
    "trailsEnabled": false,
    "trailDecay": 0.95,
    "isDefault": false,
    "shaderFile": "fishonium",
    "shader": fishoniumShader
  },
  {
    "id": "snake",
    "name": "Snake",
    "params": {
      "dt": 0.016,
      "numParticles": 3575,
      "attractionRadius": 0.2,
      "repulsionRadius": 0.03,
      "attraction": 2,
      "repulsion": 1.85,
      "alignment": 0.19,
      "friction": 2,
      "maxSpeed": 0.22,
      "mouseRadius": 0.15,
      "coneAngle": 0.55,
      "size": 0.005,
      "shapeId": 0,
      "colorR": 0.88,
      "colorG": 0.63,
      "colorB": 0.25,
      "opacity": 1.0,
      "opacityMode": 0
    },
    "trailsEnabled": false,
    "trailDecay": 0.92,
    "shaderFile": "snake",
    "shader": snakeShader
  },
  {
    "id": "particlebahn",
    "name": "ParticleBahn",
    "params": {
      "dt": 0.016,
      "numParticles": 2000,
      "attractionRadius": 0.22,
      "repulsionRadius": 0.265,
      "attraction": 2,
      "repulsion": 2.55,
      "alignment": 0.98,
      "friction": 2,
      "maxSpeed": 0.2,
      "mouseRadius": 0.15,
      "coneAngle": -0.5,
      "size": 0.005,
      "shapeId": 0,
      "colorR": 0.1450980392156863,
      "colorG": 0.09803921568627451,
      "colorB": 0.4823529411764706,
      "opacity": 1.0,
      "opacityMode": 0
    },
    "trailsEnabled": true,
    "trailDecay": 0.92,
    "shaderFile": "particlebahn",
    "shader": particlebahnShader
  }
];
