// AUTO-GENERATED by /admin/cppn — do not edit manually
import type { CPPNPreset } from '../components/simulations/cppn/cppn-types';

import softColorsWeights from './cppn-weights/soft-colors.json';
import rosesWeights from './cppn-weights/roses.json';

export type { CPPNPreset };

export const CPPN_PRESETS: CPPNPreset[] = [
  {
    "id": "soft-colors",
    "name": "Soft Colors",
    "config": {
      "zDim": 16,
      "layers": [
        {
          "width": 128,
          "activation": "tanh"
        },
        {
          "width": 12,
          "activation": "tanh"
        },
        {
          "width": 4,
          "activation": "tanh"
        }
      ],
      "distribution": {
        "type": "normal",
        "sigma": 0.9
      },
      "numBands": 4,
      "zBands": [
        {
          "freq": 0.05,
          "amplitude": 0.05,
          "phase": 0
        },
        {
          "freq": 0.05,
          "amplitude": 0.25,
          "phase": 1
        },
        {
          "freq": 0.05,
          "amplitude": 0.7,
          "phase": 0
        },
        {
          "freq": 0.05,
          "amplitude": 0.35,
          "phase": 0
        }
      ],
      "scale": 2
    },
    "seed": 1992860420,
    "isDefault": true,
    "weights": softColorsWeights
  },
  {
    "id": "roses",
    "name": "Roses",
    "config": {
      "zDim": 16,
      "layers": [
        {
          "width": 13,
          "activation": "tanh"
        },
        {
          "width": 256,
          "activation": "tanh"
        },
        {
          "width": 16,
          "activation": "tanh"
        },
        {
          "width": 4,
          "activation": "tanh"
        }
      ],
      "distribution": {
        "type": "normal",
        "sigma": 0.9
      },
      "numBands": 4,
      "zBands": [
        {
          "freq": 0.05,
          "amplitude": 0.05,
          "phase": 0
        },
        {
          "freq": 0.05,
          "amplitude": 0.1,
          "phase": 1
        },
        {
          "freq": 0.05,
          "amplitude": 0.3,
          "phase": 0
        },
        {
          "freq": 0.05,
          "amplitude": 0.2,
          "phase": 0
        }
      ],
      "scale": 1.25
    },
    "seed": 1995755334,
    "weights": rosesWeights
  }
];
