// src/data/cppn-presets.ts
// AUTO-GENERATED by /admin/cppn — do not edit manually
import type { CPPNPreset } from '../components/simulations/cppn/cppn-types';

export type { CPPNPreset };

export const CPPN_PRESETS: CPPNPreset[] = [];
