// AUTO-GENERATED by /admin/field-boids — do not edit manually
import type { FieldBoidsPreset } from '../components/simulations/field-boids/field-boids-types';

export type { FieldBoidsPreset };

export const FIELD_BOIDS_PRESETS: FieldBoidsPreset[] = [
  {
    "id": "murmuration",
    "name": "Murmuration",
    "isDefault": true,
    "params": {
      "dt": 0.016,
      "numParticles": 500000,
      "attractionRadius": 0.15,
      "repulsionRadius": 0.03,
      "attraction": 0.3,
      "repulsion": 1.5,
      "alignment": 0.1,
      "friction": 2.0,
      "maxSpeed": 0.22,
      "coneAngle": -0.5,
      "noise": 0.0,
      "mouseRadius": 0.15,
      "memory": 0.0,
      "splatSize": 1.5,
      "viewMode": 0,
      "exposure": 2.0,
      "pointAlpha": 0.15
    }
  }
];
