// AUTO-GENERATED by /admin/field-boids — do not edit manually
import type { FieldBoidsPreset } from '../components/simulations/field-boids/field-boids-types';

export type { FieldBoidsPreset };

export const FIELD_BOIDS_PRESETS: FieldBoidsPreset[] = [
  {
    "id": "murmuration",
    "name": "Murmuration",
    "params": {
      "dt": 0.016,
      "numParticles": 500000,
      "attractionRadius": 0.15,
      "repulsionRadius": 0.03,
      "attraction": 0.5,
      "repulsion": 1,
      "alignment": 2,
      "friction": 2,
      "maxSpeed": 0.22,
      "coneAngle": -0.5,
      "noise": 0.005,
      "mouseRadius": 0.15,
      "memory": 0,
      "splatSize": 1.5,
      "viewMode": 0,
      "exposure": 0.4,
      "pointAlpha": 0.15
    },
    "isDefault": true
  },
  {
    "id": "waves",
    "name": "Waves",
    "params": {
      "dt": 0.016,
      "numParticles": 500000,
      "attractionRadius": 0.15,
      "repulsionRadius": 0.03,
      "attraction": 2,
      "repulsion": 2,
      "alignment": 2,
      "friction": 2,
      "maxSpeed": 0.22,
      "coneAngle": -0.5,
      "noise": 0,
      "mouseRadius": 0.15,
      "memory": 0,
      "splatSize": 1.5,
      "viewMode": 0,
      "exposure": 0.4,
      "pointAlpha": 0.15
    }
  },
  {
    "id": "trails",
    "name": "Trails",
    "params": {
      "dt": 0.016,
      "numParticles": 500000,
      "attractionRadius": 0.15,
      "repulsionRadius": 0.03,
      "attraction": 2,
      "repulsion": 2,
      "alignment": 2,
      "friction": 2,
      "maxSpeed": 0.22,
      "coneAngle": -0.5,
      "noise": 0,
      "mouseRadius": 0.15,
      "memory": 0.92,
      "splatSize": 1.5,
      "viewMode": 0,
      "exposure": 0.1,
      "pointAlpha": 0.15
    }
  }
];
