// AUTO-GENERATED by /admin/nca — do not edit manually
import type { NCAPreset } from '../components/simulations/nca/nca-types';

import caVgg16StarryWeights from './nca-weights/ca-vgg16-starry.json';
import caVgg16ZebraWeights from './nca-weights/ca-vgg16-zebra.json';
import caVgg16CheckerboardWeights from './nca-weights/ca-vgg16-checkerboard.json';

export type { NCAPreset };

const BASE_CONFIG = {
  channels: 12 as const,
  hidden: 96 as const,
  filters: { identity: true, sobelX: true, sobelY: true, laplacian: true },
  activation: 'relu' as const,
  fireRate: 0.5,
  stepsPerFrame: 4,
  dt: 1.0,
  gridWidth: 128 as const,
  gridHeight: 128 as const,
  channelR: 0,
  channelG: 1,
  channelB: 2,
  normalizeDisplay: true,
  seedMode: 'center' as const,
};

export const NCA_PRESETS: NCAPreset[] = [
  {
    id: 'ca-vgg16-starry',
    name: 'Starry',
    isDefault: true,
    config: { ...BASE_CONFIG },
    weights: caVgg16StarryWeights,
  },
  {
    id: 'ca-vgg16-zebra',
    name: 'Zebra',
    config: { ...BASE_CONFIG },
    weights: caVgg16ZebraWeights,
  },
  {
    id: 'ca-vgg16-checkerboard',
    name: 'Checkerboard',
    config: { ...BASE_CONFIG },
    weights: caVgg16CheckerboardWeights,
  },
];
