// src/data/nca-presets.ts
// AUTO-GENERATED by /admin/nca — do not edit manually
import type { NCAPreset } from '../components/simulations/nca/nca-types';

export type { NCAPreset };

export const NCA_PRESETS: NCAPreset[] = [];
